### ISSUE TITLE
Re-design the chain selection menu

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#114]
We can refer the subsquare's implementation. Related issue: #105

**Comment by Popoulosss** [comment]
- Classify projects by chain
- When hovering over item, display caret icon

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5479%3A36137)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/195245616-6afbd0af-ab13-45ae-9391-2ad888e4d424.png">
