### ISSUE TITLE
design a 404 panel

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/statescan-v2#120]
better be universal for everything

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5676%3A28987&viewport=-3083%2C2785%2C0.25)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/194832424-b4cf8a54-9405-4bff-903c-4918e3ba2d00.png">
