### ISSUE TITLE
page home, search/explore logic

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/statescan-v2#196]
when support `assets`, `nft`

https://github.com/opensquare-network/statescan-v2/blob/f6f491f80bb4652f0b9ef2711d6ba508a2c61fb8/site/src/components/home/explore/index.js#L64-L74

https://github.com/opensquare-network/statescan-v2/blob/f6f491f80bb4652f0b9ef2711d6ba508a2c61fb8/site/src/components/home/explore/index.js#L46-L54

**Comment by wliyongfeng** [comment]
Will create a new issue when we are ready to add assets and NFT feature.
