### ISSUE TITLE
page home, search/explore UI design

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/statescan-v2#211]
figma: https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6335%3A40897

cases:

block height

<img width="602" alt="image" src="https://user-images.githubusercontent.com/19513289/196842545-ff57ce56-3af0-4220-84de-d9f4b9445169.png">

block hash

<img width="601" alt="image" src="https://user-images.githubusercontent.com/19513289/196842514-faa056dc-4ed5-4e8d-94f0-ae70976b0056.png">

extrinsic hash

<img width="601" alt="image" src="https://user-images.githubusercontent.com/19513289/196842619-d18130db-7976-4c99-aeeb-45e0adad6213.png">

address

<img width="601" alt="image" src="https://user-images.githubusercontent.com/19513289/196842679-2b9e0fd1-a149-4522-8599-dc63a5920f77.png">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6335%3A38433)

Files
[icons-20-loading-animation.svg.zip](https://github.com/opensquare-network/statescan-v2/files/9835596/icons-20-loading-animation.svg.zip)
