### ISSUE TITLE
minor style glitches

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/statescan-v2#271]
![image](https://user-images.githubusercontent.com/12393771/198233153-32d105e2-4f93-45ba-9f37-4f85bea604db.png)

**Comment by YoshiyukiSakura** [comment]
# search box line height
![image](https://user-images.githubusercontent.com/12393771/198237049-192f7a84-4d2c-4caf-8bf3-141394b0b7e9.png)
![image](https://user-images.githubusercontent.com/12393771/198237089-e323cb63-1166-4b4f-aa65-3a1d88f7b424.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6963%3A39964)
