### ISSUE TITLE
page blocks, `validator` text too long

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/statescan-v2#359]
do `text ellipsis over...`

<img width="523" alt="image" src="https://user-images.githubusercontent.com/19513289/210336774-b22fb96e-ede6-4b10-bc13-bffdc74c336f.png">

**Comment by Popoulosss** [comment]
- [ ] The text of identity overflow displays ellipses

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5527%3A38563&t=LRjzJ7phQD3zNAIu-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/210367061-892f7bd0-8e76-45b3-8d82-776b28fff8b6.png">

**Comment by Popoulosss** [comment]
- [ ] Change the width of status column to 112px
- [ ] Change the width of hash column to 240px

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/210367535-fdd08021-8103-4a8a-b8aa-559535757cb6.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/210367564-0d3d945f-251d-4303-8326-f3283b043bda.png">
