### ISSUE TITLE
assets, page assets, standalone `name` column

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/statescan-v2#362]
ref to v1 is fine.
https://statemine.statescan.io/assets?page=2

![img_v2_9efc9b38-4e80-4bbb-a90c-920997fb581g](https://user-images.githubusercontent.com/19513289/210473423-bc37f5d0-ffee-49d3-a09c-f7c0c1d758db.jpg)

**Comment by Popoulosss** [comment]
- [ ] Separate symbol and name column
- [ ] Fixed the width of symbol to 136px
- [ ] Change the fixed width of Asset ID/NFT ID columns to 120px
- [ ] Overflow text of asset name is displayed as an ellipsis
- [ ] Display whole name when hover on the asset name if the name text is overflowed

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5527%3A38563&t=RK3kVyXEgAYwdzmQ-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/210477079-edc71a25-578e-4222-88f8-2a615a25a4d2.png">
