### ISSUE TITLE
New NFT instance timeline icons

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan-v2#514]
@Popoulosss 
- [x] ItemBought
- [x] ItemPriceRemoved
- [x] ItemPriceSet

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5531%3A45313&t=xwHMIoWQ2jN91rYd-11)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/213344729-f1091c32-f5ad-435b-875a-84ac391e75d5.png">
