### ISSUE TITLE
Add new stats numbers to home summary

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/statescan-v2#515]
- [ ] Show when the stats numbers exist

![image](https://user-images.githubusercontent.com/6297057/213335731-f005c5b9-5e37-4252-867b-7bec008a3dc6.png)

**Comment by Popoulosss** [comment]
- Add 'Assets', 'NFT Class', 'NFT Instance' and 'Polkadot/Kusama Para ID'(e.g. [Statemine's Kusama para ID is 1000](https://statemine.subscan.io/))
- Relay chain has no ID

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=7688%3A41600&t=xwHMIoWQ2jN91rYd-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/213350529-66252a1c-412e-4ea1-b0fa-50a6e5763d50.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/213350532-315b9d89-ff91-4f17-9b1b-835ffa116f91.png">
