### ISSUE TITLE
Not use image background for NFT images

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#566]
NFT image has problems. Check following:

![RouShsdzqs](https://user-images.githubusercontent.com/2264908/217215985-e3b626fa-89bc-4a8c-a060-c9b0059482df.jpg)

http://localhost:3000/#/uniques/classes/8888

https://statescan-statemine-dev.on.fleek.co/#/uniques/classes/16?tab=instances&page=1

**Comment by Popoulosss** [comment]
- [ ] Change background color to #EFEFF0

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5529%3A43386&t=vQ67FVDnavsG9Ip1-11)
