### ISSUE TITLE
transfer layout

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/statescan-v2#585]
![img_v2_7d329e15-b385-46dd-a8e9-90efe13d0d9g](https://user-images.githubusercontent.com/19513289/218641404-9eb06907-5d36-4aa3-a448-8575dc374c54.jpg)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=7803%3A41762&t=fw3xPznqnyK7tQzT-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/218654486-2c6476ff-45f7-4204-b30c-1ed98b5b68f8.png">
