### ISSUE TITLE
As a user, I want to see governance status on statescan

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#633]
User story:
- There are different governance items on different chains. User should see what governance items a chain has. 
- User should see active/total governance item counts. User should be able to go to the corresponding page(subsquare/polkassembly) when clicking the count.

Solution:
Add a panel on statescan home page showing governance items statistics, and user can go to subsquare with links.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=8188-45897&t=YeeT21y60cxtoe1h-11)

Preview (TBD)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/224213398-efd69586-db27-49b0-b24f-f50acac763a2.png">
