### ISSUE TITLE
Show assets transfer list on extrinsic detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#638]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5529-43386&t=DIPzkQMOUuNIIuMf-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/228782110-3bdd653b-36a2-49b4-b69c-35e7647fe433.png">

**Comment by Popoulosss** [comment]
The default display shows 10 transferred data, with any additional data being folded.

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/229447401-ee7c66fc-376a-4688-9cd5-f81ef08dfaef.png">
