### ISSUE TITLE
I get an error when executing npm install

### ISSUE THREAD

**Issue by mil5500** [opensquare-network/statescan-v2#692]
'Log files:
/root/.npm/_logs/2023-06-23T12_28_18_040Z-debug-0.log

# npm resolution error report

While resolving: site@0.1.0
Found: react@18.2.0
node_modules/react
  react@"^18.2.0" from the root project

Could not resolve dependency:
peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
node_modules/react-json-view
  react-json-view@"^1.21.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by 2nthony** [comment]
try yarn please :) Our projects are using Yarn as package manager

```sh
npm i -g yarn
yarn
```
