### ISSUE TITLE
Show sub identities on account detail page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#769]
Currently on account detail page, we have identity/registrar timeline info. We should also implement the sub identities tab.

User story: as a member who has on-chain identity, I want to see all my sub identities, so I can use one of them to do my business.

**Comment by Popoulosss** [comment]
- [ ] Change the tab `Timeline` to `Identity`
- [ ] `isSub: false` show 4 tabs
   - [ ] Info
   - [ ] Sub Identitites
   - [ ] Idenitity Timeline
   - [ ] Registrar Timeline
- [ ] `isSub: true` show 3 tabs
   - [ ] Info
   - [ ] Sub Idenitity Timeline
   - [ ] Registrar Timeline
- [ ] If the tabs have no data, show the [empty status](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9486-45632&mode=design&t=wiH94yPMPViFhy4S-11)

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=8920-57780&mode=design&t=wiH94yPMPViFhy4S-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/108a3ec5-c04e-4b0b-82d4-14884144a49f">

**Comment by Popoulosss** [comment]
- [ ] Replace the icons

Files
[icons-data.zip](https://github.com/opensquare-network/statescan-v2/files/12546894/icons-data.zip)


Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/bfa9c1b0-d5d5-4ad0-b58f-54d190ce158e">
