### ISSUE TITLE
Search identity on home page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#800]
![LZFZpNiyHf](https://github.com/opensquare-network/statescan-v2/assets/2264908/2478c506-174c-4e04-8ec3-5f3484a88f5b)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?type=design&node-id=5464-37867&mode=design&t=l4FhREG6QhCHzWS5-11)

- When user search by address, show the results of account and identity(If there is one), refer to the [identities page](https://polkadot.statescan.io/#/identities?search=Onemai&page=1)
- When user search by identity name, show the results of identities

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/531d3976-3694-4262-b4ac-e14e62724570">
