### ISSUE TITLE
home page latest transfer section

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/statescan-v2#81]
figma link: https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=5459%3A33165

![image](https://user-images.githubusercontent.com/12393771/192970271-f6befbc3-5261-4833-97d1-1bda05c9e556.png)

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/194695520-d5ea7896-aa6e-4d5b-99c2-491dad0b3616.png)
plz complete with this

**Comment by 2nthony** [comment]
> ![image](https://user-images.githubusercontent.com/12393771/194695520-d5ea7896-aa6e-4d5b-99c2-491dad0b3616.png) plz complete with this

#91
