### ISSUE TITLE
Multisig related business UIs

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#815]
- On account detail page, there should be a tag shows this is a multisig address.
- On account detail page, there should be multisig details, including all signatories and threshold.
- On account detail page, there should be a tag where all multisig calls are shown.
- There should a multisig call list which can be filtered by address or `multisigState`.
- There should a multisig address list which can be sorted by `debutAt` or `latestMultisigAt`.
- There should a statistics panel on home page to show status of multisig.

**Comment by Popoulosss** [comment]
- [ ] On account detail page, there should be a tag shows this is a multisig address.

**Comment by Popoulosss** [comment]
- [ ] On account detail page, there should be multisig details, including all signatories and threshold.

**Comment by Popoulosss** [comment]
- [ ] On account detail page, there should be a tag where all multisig calls are shown.

**Comment by Popoulosss** [comment]
- [ ] There should a multisig call list which can be filtered by address or `multisigState`.

**Comment by Popoulosss** [comment]
- [ ] There should a multisig address list which can be sorted by `debutAt` or `latestMultisigAt`.

**Comment by Popoulosss** [comment]
- [ ] There should a statistics panel on home page to show status of multisig.

**Comment by Popoulosss** [comment]
- [ ] Show the multisig timeline (including signature status)

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9582-21987&mode=design&t=ieA3w1gL9BtzqW9a-11)

Files
[icons-multisig.zip](https://github.com/opensquare-network/statescan-v2/files/12836690/icons-multisig.zip)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/84b41dad-7fd5-4ea3-8bb9-f5d570f255b2">

**Comment by Popoulosss** [comment]
- [ ] Show the multisig in signatory account detail page
   - [ ] Multisig accounts: show the list of multisig accounts to which the signatory account belongs
   - [ ] Multisigs: show the the list of multisigs

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9645-16995&mode=design&t=uNOUwxDv9YUmNivj-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/e6fc9d0a-06cd-4801-86d1-86b32f345017">

**Comment by Popoulosss** [comment]
- [ ] Add `start time` column to the multisigs table of mutisig address
- [ ] Sorted by latest of `start time` by default

Figma linkhttps://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9573-18095&mode=design&t=BbdvsNhWA7WKfI2Z-11

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/c9e89850-0aa1-4cb1-b126-0494e0b6758b">

**Comment by Popoulosss** [comment]
Multisigs table

- [ ] Combine the `approving` and `signatories` to one column
   - [ ] Show format at: n / m · (x)
   - [ ] Show all signatories when hover over the text
- [ ] Combine the `call hash` and `call` to one column
   - [ ] Modify the width of column to 320px
- [ ] Add `start time` column to the multisigs table of mutisig address
   - [ ] Sorted by latest of `start time` by default
- [ ] Implement the accordion cell to the table for showing call detail, refer to the [multisigs table of mutisig address](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9573-18095&mode=design&t=BbdvsNhWA7WKfI2Z-11)

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v1.0?type=design&node-id=9575-18884&mode=design&t=BbdvsNhWA7WKfI2Z-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/b41fcadf-72e3-4bb6-a9ff-492e2f41b89d">

---

- [ ] Implement the above updated to the multisigs table of signatory address detail

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/9773c051-a6dc-4a72-a941-d6bf7a3c7313">
