### ISSUE TITLE
Help with Statescan setup for Edgeware 

### ISSUE THREAD

**Issue by Bharathcoorg** [opensquare-network/statescan-v2#820]
I tried to set up Statescan v2 for Edgeware but got some new errors.
Subscan stopped the explorer, and we need a new one now. Old Edgeware developers are not available to solve types of bundle errors, but I managed to create a working type bundle and sync subsquid archive nodes successfully. But the same types didn't work with Statescan. I altered node_modules for debugging but still can't solve these errors.
 
2023-10-17 22:12:12        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash)
: StorageData:: Unable to decode storage system.events:: createType(Vec<EventRec
ord>):: decodeU8aVec: failed at 0x4f751078e0a5310ac101000000000000… (index 5/5):
 {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8aStruct: faile
d at 0x4f751078e0a5310ac101000000000000… on phase (index 1/3): {"_enum":{"ApplyE
xtrinsic":"u32","Finalization":"Null","Initialization":"Null"}}:: Unable to crea
te Enum via index 79, in ApplyExtrinsic, Finalization, Initialization

**Comment by wliyongfeng** [comment]
This is an issue between polkadot.js API and edgeware AFAIK. I'm afraid you have to solve this issue with customized edgeware types.
