### ISSUE TITLE
Not save unnecessary data

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#834]
We will set a simple mode.

- [x] Not save all block data to database. Only keep latest 100 blocks in DB.
- [x] Not show block list page on fronted, while block detail data will be loaded by node.
- [x] Not show event docs and args on list page.
- [x] Only save signed extrinsic.

To be decided:

- [x] Only save extrinsic section, method, indexer and other necessary data.
- [x] Only save event section, method, indexer and other necessary event data.

**Comment by wliyongfeng** [comment]
Fronted todo:

- [ ] Add a env variable to set simple mode.
- [ ] Not show block list page in simple mode.
- [ ] Not show signed only filter on extrinsic list page.
- [ ] Not show `Extrinsic result` filter on event list page in simple mode.

@hyifeng

**Comment by Popoulosss** [comment]
@hyifeng 
Simple mode display(latest blocks)
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/7f5fefa1-c252-484c-aab4-8cc1b6045cd2">
