### ISSUE TITLE
Support bridge hub chains

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#880]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.dotters.network%2Fbridgehub-polkadot#/accounts

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?type=design&node-id=10213-25730&mode=design&t=bYvFtoVfe4g40903-11)

Files
[icons.zip](https://github.com/opensquare-network/statescan-v2/files/15074934/icons.zip)

---

Polkadot BridgeHub

Color
- theme100 `#E6007A1A`
- theme500 `#E6007A`

---

Kusama BridgeHub

Color
- theme100 `#E6007A1A`
- theme500 `#E6007A`
