### ISSUE TITLE
Polkadot-collectives fellowshipCore::submitEvidence parameters are not correctly rendered

### ISSUE THREAD

**Issue by acatangiu** [opensquare-network/statescan-v2#897]
The `wish` parameter in `fellowshipCore::submitEvidence` extrinsics is incorrectly shown as `NULL` instead of the actual enum version used.

E.g. https://collectives.statescan.io/#/extrinsics/3755964-2

**Comment by wliyongfeng** [comment]
Will check it soon. Thank you.
