### ISSUE TITLE
calls list table design

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/statescan-v2#90]

**Comment by Popoulosss** [comment]
Calls list table

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6519%3A38564)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/193244922-bff43d0f-f52e-451a-8ba4-90733a6cbbfb.png">


---

Calls detail page panel

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6534%3A39415)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/193245343-62a51186-6a3b-44bf-9ac3-caa6242df909.png">

---

Calls list table displays in extrinsic detail page

[Figma link](https://www.figma.com/file/bSUF8SniEtSOWNGsnHTEpI/Statescan?node-id=6534%3A39296)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/193245610-a31d1a2a-a6af-49fa-ac79-fb125cd992c8.png">
