### ISSUE TITLE
Support recovery pallet business

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#904]

**Comment by Popoulosss** [comment]
- Add `Recovery` entrance to `Business` dropdown menu
   - recoverables
   - recoveries

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10424-3963&t=7QRkSb14jBcye2tc-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/aac88225-6ab0-45da-bfd5-ceb033cab02e">

**Comment by Popoulosss** [comment]
- Recoverables table
   - created at (block height)
   - account
   - threshold (n · m, n=threshold, m=friends(show the all addresses in the tooltip))
   - delay period (show the time in the tooltip)
   - deposit
   - rescuer
   - status (active/inactive)
   - arrow button (link to recoverable detail page)

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10427-4400&t=7QRkSb14jBcye2tc-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/90ad2d15-4efc-4761-8c23-974f43736616">

---

- Recoverable detail
   - metadata
      - address/account
      - created at (block height)
      - removed at (block height)
      - rescuer
      - deposit
      - status
      - threshold
      - friends and all addresses/accounts
   - timeline
      - RecoveryCreated
      - RecoveryInitiated
      - RecoveryVouched
      - RecoveryClosed
      - *AccountRecovered
      - *RecoveryRemoved

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10431-6069&t=7QRkSb14jBcye2tc-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/48ad4400-76af-4aeb-9f15-ea26247afa02">

**Comment by Popoulosss** [comment]
- Recoveries table
   - created at (block)
   - lost (address/account)
   - rescuer
   - vouching (x / n · m, x=vouching(show tooltip), n=threshold, m=friends(show tooltip))
   - deposit
   - status (active/complete)

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10427-4622&t=7QRkSb14jBcye2tc-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/d8167238-36d9-47c6-88b5-d62913f542f6">

**Comment by Popoulosss** [comment]
- Add filter panel to recoverable list page, refer to [multisigs list page](https://polkadot.statescan.io/#/multisigs?page=1)
   - support searching address(lost account)
   - support filtering by status: active/inactive
   - note: no need to show the `Reset` and `Filter` button
- Switch the positions of column `Account` and column `Created at`

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10427-4400&t=VzojrDwDGrHPBX2O-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/ddeae672-1e31-452d-a3ad-3ed6c62bc4a0">

**Comment by Popoulosss** [comment]
- Implement proxy list page
   - lost account
   - rescuer

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10721-63282&t=VzojrDwDGrHPBX2O-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/f24ae20d-024e-4b95-adb9-6bf03c1bdcc0">

**Comment by Popoulosss** [comment]
- Add recoverabel stats panel to homepage(kusama)
   - recoverable: active/inactive
   - recovery: unclosed/closed
   - proxies
- User can visit recovery pages by clicking the number
- Show the tooltip when hover over the number, refer to identities stats

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10718-61500&t=VzojrDwDGrHPBX2O-11)

Files
[icons.zip](https://github.com/opensquare-network/statescan-v2/files/15463486/icons.zip)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/fddbe060-1c30-4a33-9202-7afc4c306c6a">

**Comment by Popoulosss** [comment]
Add revcoverable list to account

[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=10802-22438&t=aZtdXGeb31XinYe1-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/statescan-v2/assets/59445675/21c553a5-e7ef-4454-8986-ff641527d6d4">
