### ISSUE TITLE
Support paseo testnet

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#983]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpas-rpc.stakeworld.io#/accounts

@Popoulosss We need design stuff.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/bSUF8SniEtSOWNGsnHTEpI/Statescan-v2.0?node-id=11489-68038&node-type=frame&t=7XV5vlob6qaxGg6L-11)

Files
[icons-chain-paseo.zip](https://github.com/user-attachments/files/18057922/icons-chain-paseo.zip)

Color
- theme100 `#1CC7761A`
- theme500 `#1CC776`
